In [2]:
import numpy as n
flag = 0
arr1 = n.random.randint(5)
guess = int(input("Enter Your guess Number : "))
if guess == arr1:
    flag += 1
else:
    flage = 0
print(f"the generated number is : ", arr1)
print("your score is : ", flag)

the generated number is :  0
your score is :  0


In [11]:
# 2x + 3y = 8

# 3x + 4y = 11


A = n.array([[2, 3], [3, 4]])

B = n.array([8, 11])
print("the valuse of x and y are respectively" ,n.linalg.solve(A,B))

print("The determinent of the given matrix is : " , n.linalg.det(A))

print("___________________________________________________________________")

print(A)
print(A.T)
print(n.transpose(A))
print("___________________________________________________________________")


print(A*B)




the valuse of x and y are respectively [1. 2.]
The determinent of the given matrix is :  -1.0000000000000004
___________________________________________________________________
[[2 3]
 [3 4]]
[[2 3]
 [3 4]]
[[2 3]
 [3 4]]
___________________________________________________________________
[[16 33]
 [24 44]]


In [9]:
def is_prime(a):
    if a < 2:
        return False
    for i in range(2, int(n.sqrt(a)) + 1):
        if a % i == 0:
            return False
    return True

# Apply function to array
N = 100
numbers = n.arange(2, N+1)
primes = numbers[n.vectorize(is_prime)(numbers)]

print("Prime numbers from 1 to", N, ":\n", primes)

Prime numbers from 1 to 100 :
 [ 2  3  5  7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89
 97]
